version: "3.4"
services:
    cfee3a34e9c68ac1d16035a81a926786:
        build:
            context: .
            dockerfile: dummies/cfee3a34e9c68ac1d16035a81a926786
        image: cfee3a34e9c68ac1d16035a81a926786

    hnode_150_web:
        build: ./hnode_150_web
        image: 127.0.0.1:5000/hnode_150_web
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_150_net0:
                ipv4_address: 10.150.0.71

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "150"
            org.seedsecuritylabs.seedemu.meta.nodename: "web"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.150.0.71/24"

    rnode_150_router0:
        build: ./rnode_150_router0
        image: 127.0.0.1:5000/rnode_150_router0
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_150_net0:
                ipv4_address: 10.150.0.254
            net_ix_ix100:
                ipv4_address: 10.100.0.150

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "150"
            org.seedsecuritylabs.seedemu.meta.nodename: "router0"
            org.seedsecuritylabs.seedemu.meta.role: "Router"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.150.0.254/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.100.0.150/24"


networks:
    net_150_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.150.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "150"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.150.0.0/24"

    net_ix_ix100:
        external:
            name: sim_ix_net_ix_ix100
        driver: overlay
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "global"
            org.seedsecuritylabs.seedemu.meta.scope: "ix"
            org.seedsecuritylabs.seedemu.meta.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.100.0.0/24"



