version: "3.4"
services:
    cfee3a34e9c68ac1d16035a81a926786:
        build:
            context: .
            dockerfile: dummies/cfee3a34e9c68ac1d16035a81a926786
        image: cfee3a34e9c68ac1d16035a81a926786

    rs_ix_ix100:
        build: ./rs_ix_ix100
        image: 127.0.0.1:5000/rs_ix_ix100
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_ix_ix100:
                ipv4_address: 10.100.0.100

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "100"
            org.seedsecuritylabs.seedemu.meta.nodename: "ix100"
            org.seedsecuritylabs.seedemu.meta.role: "Route Server"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.100.0.100/24"


networks:
    net_ix_ix100:
        driver: overlay
        attachable: true
        ipam:
            config:
                - subnet: 10.100.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "global"
            org.seedsecuritylabs.seedemu.meta.scope: "ix"
            org.seedsecuritylabs.seedemu.meta.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.100.0.0/24"



